/**
 * ClassSaveMigrationMap.js — Static Unambiguous Migration Dictionary
 * 
 * Strict compliance with User Directive 12 & 13:
 * Provides unambiguous mapping: legacyId -> canonicalId, confidence, reason.
 * Total mappings: 315
 */

export const CLASS_SAVE_MIGRATION_MAP = Object.freeze({
  "fighter": Object.freeze({"canonicalId":"fighter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "humanfighter": Object.freeze({"canonicalId":"fighter","confidence":"HIGH","reason":"Legacy concatenated Human Fighter"}),
  "human_fighter": Object.freeze({"canonicalId":"fighter","confidence":"EXACT","reason":"Standard Human Fighter"}),
  "mage": Object.freeze({"canonicalId":"mage","confidence":"EXACT","reason":"Already Canonical ID"}),
  "humanmage": Object.freeze({"canonicalId":"mage","confidence":"HIGH","reason":"Legacy concatenated Human Mage"}),
  "human_mage": Object.freeze({"canonicalId":"mage","confidence":"EXACT","reason":"Standard Human Mystic"}),
  "wizard": Object.freeze({"canonicalId":"wizard","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_wizard": Object.freeze({"canonicalId":"wizard","confidence":"HIGH","reason":"Prefixed Human Wizard"}),
  "human_sorcerer": Object.freeze({"canonicalId":"sorcerer","confidence":"HIGH","reason":"Prefixed Sorcerer"}),
  "deathpilgrim": Object.freeze({"canonicalId":"human_deathknight_0","confidence":"HIGH","reason":"Legacy Death Pilgrim maps to Human Death Knight Base"}),
  "human_deathpilgrim": Object.freeze({"canonicalId":"human_deathknight_0","confidence":"HIGH","reason":"Human Death Pilgrim"}),
  "deathblade": Object.freeze({"canonicalId":"human_deathknight_1","confidence":"HIGH","reason":"Legacy Death Blade maps to Human Death Knight Stage 1"}),
  "deathknight": Object.freeze({"canonicalId":"human_deathknight_2","confidence":"HIGH","reason":"Legacy Death Knight maps to Human Death Knight Stage 2"}),
  "deathknight3": Object.freeze({"canonicalId":"human_deathknight_3","confidence":"HIGH","reason":"Legacy Death Knight Master"}),
  "wargbase": Object.freeze({"canonicalId":"werewolf_0","confidence":"HIGH","reason":"Legacy Warg Base maps to Werewolf Base"}),
  "human_warg": Object.freeze({"canonicalId":"werewolf_0","confidence":"HIGH","reason":"Legacy Human Warg"}),
  "wargs0": Object.freeze({"canonicalId":"werewolf_0","confidence":"HIGH","reason":"Legacy Warg S0"}),
  "wargs1": Object.freeze({"canonicalId":"werewolf_1","confidence":"HIGH","reason":"Legacy Warg S1"}),
  "wargs2": Object.freeze({"canonicalId":"werewolf_2","confidence":"HIGH","reason":"Legacy Warg S2"}),
  "wargs3": Object.freeze({"canonicalId":"werewolf_3","confidence":"HIGH","reason":"Legacy Warg S3"}),
  "assassinbase": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin Base maps to Male Assassin Base"}),
  "human_assassin": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Human Assassin"}),
  "assassins0": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin S0"}),
  "assassins1": Object.freeze({"canonicalId":"secret_assassin_male_1","confidence":"HIGH","reason":"Legacy Assassin S1"}),
  "assassins2": Object.freeze({"canonicalId":"secret_assassin_male_2","confidence":"HIGH","reason":"Legacy Assassin S2"}),
  "assassins3": Object.freeze({"canonicalId":"secret_assassin_male_3","confidence":"HIGH","reason":"Legacy Assassin S3"}),
  "elffighter": Object.freeze({"canonicalId":"elven_fighter","confidence":"HIGH","reason":"Legacy Elf Fighter"}),
  "elf_fighter": Object.freeze({"canonicalId":"elven_fighter","confidence":"HIGH","reason":"Legacy Elf Fighter"}),
  "elfmage": Object.freeze({"canonicalId":"elven_mage","confidence":"HIGH","reason":"Legacy Elf Mage"}),
  "elf_mage": Object.freeze({"canonicalId":"elven_mage","confidence":"HIGH","reason":"Legacy Elf Mage"}),
  "elf_deathknight": Object.freeze({"canonicalId":"elf_deathknight_0","confidence":"HIGH","reason":"Elf Death Knight Base"}),
  "darkelffighter": Object.freeze({"canonicalId":"dark_fighter","confidence":"HIGH","reason":"Legacy Dark Elf Fighter"}),
  "darkelf_fighter": Object.freeze({"canonicalId":"dark_fighter","confidence":"HIGH","reason":"Legacy Dark Elf Fighter"}),
  "dark_elf_fighter": Object.freeze({"canonicalId":"dark_fighter","confidence":"HIGH","reason":"Legacy Dark Elf Fighter"}),
  "darkelfmage": Object.freeze({"canonicalId":"dark_mage","confidence":"HIGH","reason":"Legacy Dark Elf Mage"}),
  "darkelf_mage": Object.freeze({"canonicalId":"dark_mage","confidence":"HIGH","reason":"Legacy Dark Elf Mage"}),
  "dark_elf_mage": Object.freeze({"canonicalId":"dark_mage","confidence":"HIGH","reason":"Legacy Dark Elf Mage"}),
  "darkelf_deathknight": Object.freeze({"canonicalId":"delf_deathknight_0","confidence":"HIGH","reason":"Dark Elf Death Knight Base"}),
  "darkelf_assassin": Object.freeze({"canonicalId":"secret_assassin_female_0","confidence":"HIGH","reason":"Dark Elf Assassin Female Base"}),
  "assassinde": Object.freeze({"canonicalId":"secret_assassin_female_0","confidence":"HIGH","reason":"Dark Elf Assassin"}),
  "bloodrosebase": Object.freeze({"canonicalId":"rose_vain_0","confidence":"HIGH","reason":"Legacy Blood Rose Base maps to Rose Vain 0"}),
  "bloodroses0": Object.freeze({"canonicalId":"rose_vain_0","confidence":"HIGH","reason":"Legacy Blood Rose S0"}),
  "bloodroses1": Object.freeze({"canonicalId":"rose_vain_1","confidence":"HIGH","reason":"Legacy Blood Rose S1"}),
  "bloodroses2": Object.freeze({"canonicalId":"rose_vain_2","confidence":"HIGH","reason":"Legacy Blood Rose S2"}),
  "bloodroses3": Object.freeze({"canonicalId":"rose_vain_3","confidence":"HIGH","reason":"Legacy Blood Rose S3"}),
  "bloodrose": Object.freeze({"canonicalId":"rose_vain_3","confidence":"HIGH","reason":"Legacy Blood Rose Final"}),
  "orcfighter": Object.freeze({"canonicalId":"orc_fighter","confidence":"HIGH","reason":"Legacy Orc Fighter"}),
  "orc_fighter": Object.freeze({"canonicalId":"orc_fighter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orcmage": Object.freeze({"canonicalId":"orc_mage","confidence":"HIGH","reason":"Legacy Orc Mage"}),
  "orc_mage": Object.freeze({"canonicalId":"orc_mage","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rider": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Rider maps to Orc Rider 0"}),
  "orcrider": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Orc Rider"}),
  "orc_rider": Object.freeze({"canonicalId":"orc_rider_0","confidence":"EXACT","reason":"Canonical Orc Rider Base"}),
  "dragoon": Object.freeze({"canonicalId":"orc_rider_1","confidence":"HIGH","reason":"Legacy Dragoon maps to Orc Rider 1"}),
  "vanguardrider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider maps to Orc Rider 2"}),
  "orc_vanguard_rider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider"}),
  "grandvanguard": Object.freeze({"canonicalId":"orc_rider_3","confidence":"HIGH","reason":"Legacy Grand Vanguard maps to Orc Rider 3"}),
  "dwarffighter": Object.freeze({"canonicalId":"dwarven_fighter","confidence":"HIGH","reason":"Legacy Dwarf Fighter"}),
  "dwarf_fighter": Object.freeze({"canonicalId":"dwarven_fighter","confidence":"HIGH","reason":"Legacy Dwarf Fighter"}),
  "dwarvenfighter": Object.freeze({"canonicalId":"dwarven_fighter","confidence":"HIGH","reason":"Dwarven Fighter"}),
  "shinemakerbase": Object.freeze({"canonicalId":"shineMakerBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shinemakers1": Object.freeze({"canonicalId":"shineMakerS1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shinemakers2": Object.freeze({"canonicalId":"shineMakerS2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shinemakers3": Object.freeze({"canonicalId":"shinemaker","confidence":"HIGH","reason":"Canonical Shine Maker Final"}),
  "kamaelsoldier": Object.freeze({"canonicalId":"jin_kamael_soldier","confidence":"HIGH","reason":"Legacy Kamael Soldier"}),
  "kamael_soldier": Object.freeze({"canonicalId":"jin_kamael_soldier","confidence":"HIGH","reason":"Legacy Kamael Soldier"}),
  "samuraibase": Object.freeze({"canonicalId":"crow_0","confidence":"HIGH","reason":"Legacy Samurai Base maps to Crow 0"}),
  "kamael_samurai": Object.freeze({"canonicalId":"crow_0","confidence":"HIGH","reason":"Legacy Kamael Samurai"}),
  "hatamoto": Object.freeze({"canonicalId":"crow_1","confidence":"HIGH","reason":"Legacy Hatamoto maps to Crow 1"}),
  "ronin": Object.freeze({"canonicalId":"crow_2","confidence":"HIGH","reason":"Legacy Ronin maps to Crow 2"}),
  "samurai": Object.freeze({"canonicalId":"crow_3","confidence":"HIGH","reason":"Legacy Samurai maps to Crow 3"}),
  "soulbreaker": Object.freeze({"canonicalId":"soul_breaker","confidence":"HIGH","reason":"Legacy Soul Breaker"}),
  "soulbreakerkamael": Object.freeze({"canonicalId":"soul_breaker","confidence":"HIGH","reason":"Legacy Soul Breaker"}),
  "sylphgunner": Object.freeze({"canonicalId":"sylphid","confidence":"HIGH","reason":"Legacy Sylph Gunner maps to Sylphid Base"}),
  "sylph_gunner_base": Object.freeze({"canonicalId":"sylphid","confidence":"HIGH","reason":"Legacy Sylph Base"}),
  "sharpshooter": Object.freeze({"canonicalId":"sylph_gunner","confidence":"HIGH","reason":"Legacy Sharpshooter maps to Sylph Gunner Stage 1"}),
  "windsniper": Object.freeze({"canonicalId":"wind_hunter","confidence":"HIGH","reason":"Legacy Wind Sniper maps to Wind Hunter Stage 2"}),
  "stormblaster": Object.freeze({"canonicalId":"storm_blaster","confidence":"EXACT","reason":"Canonical Storm Blaster"}),
  "divinetemplarbase": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"HIGH","reason":"Legacy Divine Templar Base"}),
  "divinetemplars1": Object.freeze({"canonicalId":"sacred_templar_1","confidence":"HIGH","reason":"Legacy Divine Templar S1"}),
  "divinetemplars2": Object.freeze({"canonicalId":"sacred_templar_2","confidence":"HIGH","reason":"Legacy Divine Templar S2"}),
  "divinetemplars3": Object.freeze({"canonicalId":"sacred_templar_3","confidence":"HIGH","reason":"Legacy Divine Templar S3"}),
  "elementweaverbase": Object.freeze({"canonicalId":"spirit_0","confidence":"HIGH","reason":"Legacy Element Weaver Base"}),
  "elementweavers1": Object.freeze({"canonicalId":"spirit_1","confidence":"HIGH","reason":"Legacy Element Weaver S1"}),
  "elementweavers2": Object.freeze({"canonicalId":"spirit_2","confidence":"HIGH","reason":"Legacy Element Weaver S2"}),
  "elementweavers3": Object.freeze({"canonicalId":"spirit_3","confidence":"HIGH","reason":"Legacy Element Weaver S3"}),
  "highelfbase": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"MEDIUM","reason":"Default High Elf Base"}),
  "marauderbase": Object.freeze({"canonicalId":"marauderBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayhamagebase": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "assassin": Object.freeze({"canonicalId":"assassin","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_assassinbase": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin S0"}),
  "human_assassins0": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin S0"}),
  "darkelf_assassinbase": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin S0"}),
  "darkelf_assassins0": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"HIGH","reason":"Legacy Assassin S0"}),
  "darkelf_deathpilgrim": Object.freeze({"canonicalId":"human_deathknight_0","confidence":"HIGH","reason":"Legacy Death Pilgrim maps to Human Death Knight Base"}),
  "elfdeathpilgrim": Object.freeze({"canonicalId":"human_deathknight_0","confidence":"HIGH","reason":"Legacy Death Pilgrim maps to Human Death Knight Base"}),
  "warg": Object.freeze({"canonicalId":"werewolf_0","confidence":"HIGH","reason":"Legacy Warg Base maps to Werewolf Base"}),
  "human_wargbase": Object.freeze({"canonicalId":"werewolf_0","confidence":"HIGH","reason":"Legacy Warg Base maps to Werewolf Base"}),
  "vanguard": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Rider maps to Orc Rider 0"}),
  "vanguardbase": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Rider maps to Orc Rider 0"}),
  "orc_vanguard": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Rider maps to Orc Rider 0"}),
  "orc_vanguardbase": Object.freeze({"canonicalId":"orc_rider_0","confidence":"HIGH","reason":"Legacy Rider maps to Orc Rider 0"}),
  "orcdragoon": Object.freeze({"canonicalId":"orc_rider_1","confidence":"HIGH","reason":"Legacy Dragoon maps to Orc Rider 1"}),
  "orc_dragoon": Object.freeze({"canonicalId":"orc_rider_1","confidence":"HIGH","reason":"Legacy Dragoon maps to Orc Rider 1"}),
  "ertheia_vanguard_rider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider"}),
  "ertheia_vanguardrider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider"}),
  "orc_vanguardrider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider maps to Orc Rider 2"}),
  "vanguard_rider": Object.freeze({"canonicalId":"orc_rider_2","confidence":"HIGH","reason":"Legacy Vanguard Rider maps to Orc Rider 2"}),
  "grand_vanguard": Object.freeze({"canonicalId":"orc_rider_3","confidence":"HIGH","reason":"Legacy Grand Vanguard maps to Orc Rider 3"}),
  "vanguardlord": Object.freeze({"canonicalId":"orc_rider_3","confidence":"HIGH","reason":"Legacy Grand Vanguard maps to Orc Rider 3"}),
  "scavenger": Object.freeze({"canonicalId":"scavenger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dwarf_scavenger": Object.freeze({"canonicalId":"scavenger","confidence":"EXACT","reason":"Direct canonical alias"}),
  "dwarf_shinemaker": Object.freeze({"canonicalId":"shineMakerBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "dwarf_shinemakerbase": Object.freeze({"canonicalId":"shineMakerBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "shinemaker": Object.freeze({"canonicalId":"shinemaker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "bushi": Object.freeze({"canonicalId":"crow_0","confidence":"HIGH","reason":"Legacy Samurai Base maps to Crow 0"}),
  "kamael_samuraibase": Object.freeze({"canonicalId":"crow_0","confidence":"HIGH","reason":"Legacy Samurai Base maps to Crow 0"}),
  "kamael_bushi": Object.freeze({"canonicalId":"crow_0","confidence":"HIGH","reason":"Legacy Samurai Base maps to Crow 0"}),
  "sylph_gunner": Object.freeze({"canonicalId":"sylph_gunner","confidence":"EXACT","reason":"Already Canonical ID"}),
  "highelf_base": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"MEDIUM","reason":"Default High Elf Base"}),
  "highelf_templar": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"HIGH","reason":"Legacy Divine Templar Base"}),
  "highelf_templarbase": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"HIGH","reason":"Legacy Divine Templar Base"}),
  "darkelf_bloodrose": Object.freeze({"canonicalId":"rose_vain_0","confidence":"HIGH","reason":"Legacy Blood Rose Base maps to Rose Vain 0"}),
  "darkelf_bloodrosebase": Object.freeze({"canonicalId":"rose_vain_0","confidence":"HIGH","reason":"Legacy Blood Rose Base maps to Rose Vain 0"}),
  "ertheia_fighter": Object.freeze({"canonicalId":"marauderBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "ertheia_marauderbase": Object.freeze({"canonicalId":"marauderBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "marauder": Object.freeze({"canonicalId":"marauder","confidence":"EXACT","reason":"Already Canonical ID"}),
  "eviscerator": Object.freeze({"canonicalId":"eviscerator","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayhaseekerbase": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "sayha_mage": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "sayhaseer": Object.freeze({"canonicalId":"sayhaSeer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayha_seer": Object.freeze({"canonicalId":"sayhaSeer","confidence":"EXACT","reason":"Direct canonical alias"}),
  "ertheia_mage": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "ertheia_sayhamagebase": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Direct canonical alias"}),
  "sayhaseeker": Object.freeze({"canonicalId":"sayhaSeeker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "gladiator": Object.freeze({"canonicalId":"gladiator","confidence":"EXACT","reason":"Already Canonical ID"}),
  "warlord": Object.freeze({"canonicalId":"warlord","confidence":"EXACT","reason":"Already Canonical ID"}),
  "paladin": Object.freeze({"canonicalId":"paladin","confidence":"EXACT","reason":"Already Canonical ID"}),
  "darkavenger": Object.freeze({"canonicalId":"dark_avenger","confidence":"HIGH","reason":"CamelCase darkAvenger to snake_case"}),
  "treasurehunter": Object.freeze({"canonicalId":"treasure_hunter","confidence":"HIGH","reason":"CamelCase treasureHunter to snake_case"}),
  "hawkeye": Object.freeze({"canonicalId":"hawkeye","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sorcerer": Object.freeze({"canonicalId":"sorcerer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "necromancer": Object.freeze({"canonicalId":"necromancer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "warlock": Object.freeze({"canonicalId":"warlock","confidence":"EXACT","reason":"Already Canonical ID"}),
  "bishop": Object.freeze({"canonicalId":"bishop","confidence":"EXACT","reason":"Already Canonical ID"}),
  "prophet": Object.freeze({"canonicalId":"prophet","confidence":"EXACT","reason":"Already Canonical ID"}),
  "templeknight": Object.freeze({"canonicalId":"temple_knight","confidence":"HIGH","reason":"CamelCase templeKnight to snake_case"}),
  "silverranger": Object.freeze({"canonicalId":"silver_ranger","confidence":"HIGH","reason":"CamelCase silverRanger to snake_case"}),
  "spellsinger": Object.freeze({"canonicalId":"spellsinger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elementalsummoner": Object.freeze({"canonicalId":"elemental_summoner","confidence":"HIGH","reason":"CamelCase elementalSummoner to snake_case"}),
  "shillienknight": Object.freeze({"canonicalId":"shillien_knight","confidence":"HIGH","reason":"CamelCase shillienKnight to snake_case"}),
  "abysswalker": Object.freeze({"canonicalId":"abyss_walker","confidence":"HIGH","reason":"CamelCase abyssWalker to snake_case"}),
  "phantomranger": Object.freeze({"canonicalId":"phantom_ranger","confidence":"HIGH","reason":"CamelCase phantomRanger to snake_case"}),
  "spellhowler": Object.freeze({"canonicalId":"spellhowler","confidence":"EXACT","reason":"Already Canonical ID"}),
  "phantomsummoner": Object.freeze({"canonicalId":"phantom_summoner","confidence":"HIGH","reason":"CamelCase phantomSummoner to snake_case"}),
  "shillienelder": Object.freeze({"canonicalId":"shillien_elder","confidence":"HIGH","reason":"CamelCase shillienElder to snake_case"}),
  "destroyer": Object.freeze({"canonicalId":"destroyer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "tyrant": Object.freeze({"canonicalId":"tyrant","confidence":"EXACT","reason":"Already Canonical ID"}),
  "overlord": Object.freeze({"canonicalId":"overlord","confidence":"EXACT","reason":"Already Canonical ID"}),
  "warcryer": Object.freeze({"canonicalId":"warcryer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "bountyhunter": Object.freeze({"canonicalId":"bounty_hunter","confidence":"HIGH","reason":"CamelCase bountyHunter to snake_case"}),
  "warsmith": Object.freeze({"canonicalId":"warsmith","confidence":"EXACT","reason":"Already Canonical ID"}),
  "duelist": Object.freeze({"canonicalId":"duelist","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dreadnought": Object.freeze({"canonicalId":"dreadnought","confidence":"EXACT","reason":"Already Canonical ID"}),
  "phoenixknight": Object.freeze({"canonicalId":"phoenix_knight","confidence":"HIGH","reason":"CamelCase phoenixKnight to snake_case"}),
  "hellknight": Object.freeze({"canonicalId":"hell_knight","confidence":"HIGH","reason":"CamelCase hellKnight to snake_case"}),
  "sagittarius": Object.freeze({"canonicalId":"sagittarius","confidence":"EXACT","reason":"Already Canonical ID"}),
  "adventurer": Object.freeze({"canonicalId":"adventurer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "archmage": Object.freeze({"canonicalId":"archmage","confidence":"EXACT","reason":"Already Canonical ID"}),
  "soultaker": Object.freeze({"canonicalId":"soultaker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "arcanaLord": Object.freeze({"canonicalId":"arcana_lord","confidence":"HIGH","reason":"CamelCase arcanaLord to snake_case"}),
  "arcanalord": Object.freeze({"canonicalId":"arcana_lord","confidence":"HIGH","reason":"CamelCase arcanaLord to snake_case"}),
  "cardinal": Object.freeze({"canonicalId":"cardinal","confidence":"EXACT","reason":"Already Canonical ID"}),
  "hierophant": Object.freeze({"canonicalId":"hierophant","confidence":"EXACT","reason":"Already Canonical ID"}),
  "swordmuse": Object.freeze({"canonicalId":"sword_muse","confidence":"HIGH","reason":"CamelCase swordMuse to snake_case"}),
  "windrider": Object.freeze({"canonicalId":"wind_rider","confidence":"HIGH","reason":"CamelCase windRider to snake_case"}),
  "moonlightsentinel": Object.freeze({"canonicalId":"moonlight_sentinel","confidence":"HIGH","reason":"CamelCase moonlightSentinel to snake_case"}),
  "mysticmuse": Object.freeze({"canonicalId":"mystic_muse","confidence":"HIGH","reason":"CamelCase mysticMuse to snake_case"}),
  "elementalmaster": Object.freeze({"canonicalId":"elemental_master","confidence":"HIGH","reason":"CamelCase elementalMaster to snake_case"}),
  "shillientemplar": Object.freeze({"canonicalId":"shillien_templar","confidence":"HIGH","reason":"CamelCase shillienTemplar to snake_case"}),
  "spectraldancer": Object.freeze({"canonicalId":"spectral_dancer","confidence":"HIGH","reason":"CamelCase spectralDancer to snake_case"}),
  "ghosthunter": Object.freeze({"canonicalId":"ghost_hunter","confidence":"HIGH","reason":"CamelCase ghostHunter to snake_case"}),
  "ghostsentinel": Object.freeze({"canonicalId":"ghost_sentinel","confidence":"HIGH","reason":"CamelCase ghostSentinel to snake_case"}),
  "stormscreamer": Object.freeze({"canonicalId":"storm_screamer","confidence":"HIGH","reason":"CamelCase stormScreamer to snake_case"}),
  "spectralmaster": Object.freeze({"canonicalId":"spectral_master","confidence":"HIGH","reason":"CamelCase spectralMaster to snake_case"}),
  "shilliensaint": Object.freeze({"canonicalId":"shillien_saint","confidence":"HIGH","reason":"CamelCase shillienSaint to snake_case"}),
  "titan": Object.freeze({"canonicalId":"titan","confidence":"EXACT","reason":"Already Canonical ID"}),
  "grandkhavatari": Object.freeze({"canonicalId":"grand_khavatari","confidence":"HIGH","reason":"CamelCase grandKhavatari to snake_case"}),
  "dominator": Object.freeze({"canonicalId":"dominator","confidence":"EXACT","reason":"Already Canonical ID"}),
  "doomcryer": Object.freeze({"canonicalId":"doomcryer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "fortuneSeeker": Object.freeze({"canonicalId":"fortune_seeker","confidence":"HIGH","reason":"CamelCase fortuneSeeker to snake_case"}),
  "fortuneseeker": Object.freeze({"canonicalId":"fortune_seeker","confidence":"HIGH","reason":"CamelCase fortuneSeeker to snake_case"}),
  "maestro": Object.freeze({"canonicalId":"maestro","confidence":"EXACT","reason":"Already Canonical ID"}),
  "warrior": Object.freeze({"canonicalId":"warrior","confidence":"EXACT","reason":"Already Canonical ID"}),
  "knight": Object.freeze({"canonicalId":"knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "phoenix_knight": Object.freeze({"canonicalId":"phoenix_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dark_avenger": Object.freeze({"canonicalId":"dark_avenger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "hell_knight": Object.freeze({"canonicalId":"hell_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rogue": Object.freeze({"canonicalId":"rogue","confidence":"EXACT","reason":"Already Canonical ID"}),
  "treasure_hunter": Object.freeze({"canonicalId":"treasure_hunter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "arcana_lord": Object.freeze({"canonicalId":"arcana_lord","confidence":"EXACT","reason":"Already Canonical ID"}),
  "cleric": Object.freeze({"canonicalId":"cleric","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_deathknight_0": Object.freeze({"canonicalId":"human_deathknight_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_deathknight_1": Object.freeze({"canonicalId":"human_deathknight_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_deathknight_2": Object.freeze({"canonicalId":"human_deathknight_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "human_deathknight_3": Object.freeze({"canonicalId":"human_deathknight_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_male_0": Object.freeze({"canonicalId":"secret_assassin_male_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_male_1": Object.freeze({"canonicalId":"secret_assassin_male_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_male_2": Object.freeze({"canonicalId":"secret_assassin_male_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_male_3": Object.freeze({"canonicalId":"secret_assassin_male_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "werewolf_0": Object.freeze({"canonicalId":"werewolf_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "werewolf_1": Object.freeze({"canonicalId":"werewolf_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "werewolf_2": Object.freeze({"canonicalId":"werewolf_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "werewolf_3": Object.freeze({"canonicalId":"werewolf_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elven_fighter": Object.freeze({"canonicalId":"elven_fighter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elven_knight": Object.freeze({"canonicalId":"elven_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "temple_knight": Object.freeze({"canonicalId":"temple_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "evas_templar": Object.freeze({"canonicalId":"evas_templar","confidence":"EXACT","reason":"Already Canonical ID"}),
  "swordsinger": Object.freeze({"canonicalId":"swordsinger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sword_muse": Object.freeze({"canonicalId":"sword_muse","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elven_scout": Object.freeze({"canonicalId":"elven_scout","confidence":"EXACT","reason":"Already Canonical ID"}),
  "plain_walker": Object.freeze({"canonicalId":"plain_walker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "wind_rider": Object.freeze({"canonicalId":"wind_rider","confidence":"EXACT","reason":"Already Canonical ID"}),
  "silver_ranger": Object.freeze({"canonicalId":"silver_ranger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "moonlight_sentinel": Object.freeze({"canonicalId":"moonlight_sentinel","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elven_mage": Object.freeze({"canonicalId":"elven_mage","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elven_wizard": Object.freeze({"canonicalId":"elven_wizard","confidence":"EXACT","reason":"Already Canonical ID"}),
  "mystic_muse": Object.freeze({"canonicalId":"mystic_muse","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elemental_summoner": Object.freeze({"canonicalId":"elemental_summoner","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elemental_master": Object.freeze({"canonicalId":"elemental_master","confidence":"EXACT","reason":"Already Canonical ID"}),
  "oracle": Object.freeze({"canonicalId":"oracle","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elder": Object.freeze({"canonicalId":"elder","confidence":"EXACT","reason":"Already Canonical ID"}),
  "evas_saint": Object.freeze({"canonicalId":"evas_saint","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elf_deathknight_0": Object.freeze({"canonicalId":"elf_deathknight_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elf_deathknight_1": Object.freeze({"canonicalId":"elf_deathknight_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elf_deathknight_2": Object.freeze({"canonicalId":"elf_deathknight_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "elf_deathknight_3": Object.freeze({"canonicalId":"elf_deathknight_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dark_fighter": Object.freeze({"canonicalId":"dark_fighter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "palus_knight": Object.freeze({"canonicalId":"palus_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shillien_knight": Object.freeze({"canonicalId":"shillien_knight","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shillien_templar": Object.freeze({"canonicalId":"shillien_templar","confidence":"EXACT","reason":"Already Canonical ID"}),
  "bladedancer": Object.freeze({"canonicalId":"bladedancer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spectral_dancer": Object.freeze({"canonicalId":"spectral_dancer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "abyss_walker": Object.freeze({"canonicalId":"abyss_walker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "ghost_hunter": Object.freeze({"canonicalId":"ghost_hunter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "phantom_ranger": Object.freeze({"canonicalId":"phantom_ranger","confidence":"EXACT","reason":"Already Canonical ID"}),
  "ghost_sentinel": Object.freeze({"canonicalId":"ghost_sentinel","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dark_mage": Object.freeze({"canonicalId":"dark_mage","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dark_wizard": Object.freeze({"canonicalId":"dark_wizard","confidence":"EXACT","reason":"Already Canonical ID"}),
  "storm_screamer": Object.freeze({"canonicalId":"storm_screamer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "phantom_summoner": Object.freeze({"canonicalId":"phantom_summoner","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spectral_master": Object.freeze({"canonicalId":"spectral_master","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shillien_oracle": Object.freeze({"canonicalId":"shillien_oracle","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shillien_elder": Object.freeze({"canonicalId":"shillien_elder","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shillien_saint": Object.freeze({"canonicalId":"shillien_saint","confidence":"EXACT","reason":"Already Canonical ID"}),
  "delf_deathknight_0": Object.freeze({"canonicalId":"delf_deathknight_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "delf_deathknight_1": Object.freeze({"canonicalId":"delf_deathknight_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "delf_deathknight_2": Object.freeze({"canonicalId":"delf_deathknight_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "delf_deathknight_3": Object.freeze({"canonicalId":"delf_deathknight_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_female_0": Object.freeze({"canonicalId":"secret_assassin_female_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_female_1": Object.freeze({"canonicalId":"secret_assassin_female_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_female_2": Object.freeze({"canonicalId":"secret_assassin_female_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "secret_assassin_female_3": Object.freeze({"canonicalId":"secret_assassin_female_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rose_vain_0": Object.freeze({"canonicalId":"rose_vain_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rose_vain_1": Object.freeze({"canonicalId":"rose_vain_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rose_vain_2": Object.freeze({"canonicalId":"rose_vain_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "rose_vain_3": Object.freeze({"canonicalId":"rose_vain_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_raider": Object.freeze({"canonicalId":"orc_raider","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_monk": Object.freeze({"canonicalId":"orc_monk","confidence":"EXACT","reason":"Already Canonical ID"}),
  "grand_khavatari": Object.freeze({"canonicalId":"grand_khavatari","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_shaman": Object.freeze({"canonicalId":"orc_shaman","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_rider_0": Object.freeze({"canonicalId":"orc_rider_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_rider_1": Object.freeze({"canonicalId":"orc_rider_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_rider_2": Object.freeze({"canonicalId":"orc_rider_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "orc_rider_3": Object.freeze({"canonicalId":"orc_rider_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "dwarven_fighter": Object.freeze({"canonicalId":"dwarven_fighter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "bounty_hunter": Object.freeze({"canonicalId":"bounty_hunter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "fortune_seeker": Object.freeze({"canonicalId":"fortune_seeker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "artisan": Object.freeze({"canonicalId":"artisan","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shineMakerBase": Object.freeze({"canonicalId":"shineMakerBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shineMakerS1": Object.freeze({"canonicalId":"shineMakerS1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "shineMakerS2": Object.freeze({"canonicalId":"shineMakerS2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "jin_kamael_soldier": Object.freeze({"canonicalId":"jin_kamael_soldier","confidence":"EXACT","reason":"Already Canonical ID"}),
  "trooper": Object.freeze({"canonicalId":"trooper","confidence":"EXACT","reason":"Already Canonical ID"}),
  "berserker": Object.freeze({"canonicalId":"berserker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "doombringer": Object.freeze({"canonicalId":"doombringer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "soul_finder": Object.freeze({"canonicalId":"soul_finder","confidence":"EXACT","reason":"Already Canonical ID"}),
  "soul_breaker": Object.freeze({"canonicalId":"soul_breaker","confidence":"EXACT","reason":"Already Canonical ID"}),
  "soul_hound": Object.freeze({"canonicalId":"soul_hound","confidence":"EXACT","reason":"Already Canonical ID"}),
  "warder": Object.freeze({"canonicalId":"warder","confidence":"EXACT","reason":"Already Canonical ID"}),
  "arbalester": Object.freeze({"canonicalId":"arbalester","confidence":"EXACT","reason":"Already Canonical ID"}),
  "trickster": Object.freeze({"canonicalId":"trickster","confidence":"EXACT","reason":"Already Canonical ID"}),
  "crow_0": Object.freeze({"canonicalId":"crow_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "crow_1": Object.freeze({"canonicalId":"crow_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "crow_2": Object.freeze({"canonicalId":"crow_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "crow_3": Object.freeze({"canonicalId":"crow_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sylphid": Object.freeze({"canonicalId":"sylphid","confidence":"EXACT","reason":"Already Canonical ID"}),
  "wind_hunter": Object.freeze({"canonicalId":"wind_hunter","confidence":"EXACT","reason":"Already Canonical ID"}),
  "storm_blaster": Object.freeze({"canonicalId":"storm_blaster","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sacred_templar_0": Object.freeze({"canonicalId":"sacred_templar_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sacred_templar_1": Object.freeze({"canonicalId":"sacred_templar_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sacred_templar_2": Object.freeze({"canonicalId":"sacred_templar_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sacred_templar_3": Object.freeze({"canonicalId":"sacred_templar_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spirit_0": Object.freeze({"canonicalId":"spirit_0","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spirit_1": Object.freeze({"canonicalId":"spirit_1","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spirit_2": Object.freeze({"canonicalId":"spirit_2","confidence":"EXACT","reason":"Already Canonical ID"}),
  "spirit_3": Object.freeze({"canonicalId":"spirit_3","confidence":"EXACT","reason":"Already Canonical ID"}),
  "marauderBase": Object.freeze({"canonicalId":"marauderBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "ertheiaWarrior": Object.freeze({"canonicalId":"ertheiaWarrior","confidence":"EXACT","reason":"Already Canonical ID"}),
  "ertheiawarrior": Object.freeze({"canonicalId":"ertheiaWarrior","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayhaMageBase": Object.freeze({"canonicalId":"sayhaMageBase","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayhaSeer": Object.freeze({"canonicalId":"sayhaSeer","confidence":"EXACT","reason":"Already Canonical ID"}),
  "windRiderErth": Object.freeze({"canonicalId":"windRiderErth","confidence":"EXACT","reason":"Already Canonical ID"}),
  "windridererth": Object.freeze({"canonicalId":"windRiderErth","confidence":"EXACT","reason":"Already Canonical ID"}),
  "sayhaSeeker": Object.freeze({"canonicalId":"sayhaSeeker","confidence":"EXACT","reason":"Already Canonical ID"}),
});

export default CLASS_SAVE_MIGRATION_MAP;
